main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import base
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('', include('myapp.urls')),  # myappのURLパターンを追加
    path('polls/', include('polls.urls')),
    path('album/', include('album.urls')),
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('accounts/login/', base.RedirectView.as_view(pattern_name="polls:login")),
    path('accounts/profile/', base.RedirectView.as_view(pattern_name="polls:index")),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="polls/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="polls:index"), name='logout'),
]

polls/models.py
import datetime
from django.utils import timezone
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    
    from django.db import models

    class YourModel(models.Model):
    # モデルのフィールドを定義
        name = models.CharField(max_length=100)
    # 他のフィールドも追加するか、実際のモデル定義に合わせる

polls/forms.py
from django import forms
from .models import Question, Choice
from django.contrib.auth.models import User


"""
class VoteForm(forms.Form):
    CHOICES = [(ch.id, ch.choice_text) for ch in Choice.objects.all()]
    # your_choice = forms.ChoiceField(choices = CHOICES)
    your_choice = forms.ChoiceField(choices = CHOICES, widget=forms.RadioSelect())

    def save(self):
        choice_id = self.cleaned_data.get('your_choice')
        selected_choice = Choice.objects.get(pk=choice_id)
        selected_choice.votes += 1
        selected_choice.save()

class VoteForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.question = kwargs.pop('question')
        super(VoteForm, self).__init__(*args, **kwargs)
        CHOICES = [(ch.id, ch.choice_text) for ch in self.question.choice_set.all()]
        self.fields['your_choice'] = forms.ChoiceField(choices = CHOICES, widget=forms.RadioSelect())

    def save(self):
        choice_id = self.cleaned_data.get('your_choice')
        selected_choice = Choice.objects.get(pk=choice_id)
        selected_choice.votes += 1
        selected_choice.save()
"""

class VoteForm(forms.Form):
    new_option = forms.CharField(max_length=200, required=False)

    def __init__(self, *args, **kwargs):
        self.question = kwargs.pop('question')
        super(VoteForm, self).__init__(*args, **kwargs)
        CHOICES = [(ch.id, ch.choice_text) for ch in self.question.choice_set.all()]
        CHOICES.append((-1, 'other option (please specify in the box below)'))
        self.fields['your_choice'] = forms.ChoiceField(choices = CHOICES, widget=forms.RadioSelect())

    def clean_your_choice(self):
        your_choice = self.cleaned_data.get('your_choice')
        return int(your_choice)

    def clean(self):
        cleaned_data = super(VoteForm, self).clean()
        choice_id = self.cleaned_data.get('your_choice')
        new_option = self.cleaned_data.get('new_option')
        if choice_id < 0:
            if not new_option:
                raise forms.ValidationError(
                    'Please specify a new option (or choose an existing one)!'
                    )
        else:
            if new_option:
                raise forms.ValidationError(
                    'Do not specify a new option with also choosing an existing one!'
                    )

    def save(self):
        choice_id = self.cleaned_data.get('your_choice')
        if choice_id < 0:
            new_option = Choice(
                question=self.question,
                choice_text=self.cleaned_data.get('new_option'),
                votes=1
                )
            new_option.save()
        else:
            selected_choice = Choice.objects.get(pk=choice_id)
            selected_choice.votes += 1
            selected_choice.save()


class SignUpForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput)
    enter_password = forms.CharField(widget=forms.PasswordInput)
    retype_password = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('The username has been already taken.')
        return username

    def clean_enter_password(self):
        password = self.cleaned_data.get('enter_password')
        if len(password) < 5:
            raise forms.ValidationError('Password must contain 5 or more characters.')
        return password

    def clean(self):
        super(SignUpForm, self).clean()
        password = self.cleaned_data.get('enter_password')
        retyped = self.cleaned_data.get('retype_password')
        if password and retyped and (password != retyped):
            self.add_error('retype_password', 'This does not match with the above.')

    def save(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('enter_password')
        new_user = User.objects.create_user(username = username)
        new_user.set_password(password)
        new_user.save()

polls/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Question, Choice
from .forms import *

"""
def index(request):
    return HttpResponse("Hello, world!")
"""

def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

"""
def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)
    
def detail(request, question_id):
    context = {'question_id': question_id}
    return render(request, 'polls/detail.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    choice_list = question.choice_set.all()
    context = {'question': question, 'choice_list':choice_list}
    return render(request, 'polls/detail.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    choice_list = question.choice_set.all()
    context = {'question': question, 'choice_list':choice_list}
    return render(request, 'polls/detail.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        # form = VoteForm(request.POST)
        form = VoteForm(request.POST, question=question)
        if form.is_valid():
            form.save()
            return redirect('polls:results', question_id=question.id)
    else:
        # form = VoteForm()
        form = VoteForm(question=question)

    context = {'question':question, 'form':form}
    return render(request, "polls/detail.html", context)
"""

@login_required
def detail(request, question_id):
    user = request.user
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        form = VoteForm(request.POST, question=question)
        if form.is_valid():
            form.save()
            return redirect('polls:results', question_id=question.id)
    else:
        form = VoteForm(question=question)

    context = {'user':user, 'question':question, 'form':form}
    return render(request, "polls/detail.html", context)

"""
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)
"""

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('polls:index')
    else:
        form = SignUpForm()

    context = {'form':form}
    return render(request, 'polls/signup.html', context)

# polls/views.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    # 他のURLパターン
]

polls/templates/polls/detail.html
{% extends "myapp/base.html" %}

{% load static %}


{% block title %}Home{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">
<p>ようこそ{{ user|title }}さん!　良かった</p>
<h1> {{ question.question_text }}</h1>
{{ form.non_field_errors }}
<form action="{% url 'polls:detail' question.id %}" method="post">
{% csrf_token %}
<p>
    {{ form.your_choice.label }}<br>
    {{ form.your_choice }}
</p>
<p>
    {{ form.new_option.label }}<br>
    {{ form.new_option }}
</p>
<input type="submit" value="投票する">
</form>
<p>or <a href= "{% url 'polls:logout' %}">Logout</a></p>

{% endblock %}

polls/templates/polls/detail_1.html
<h1>Question #{{ question_id }} 1</h1>
<P>detail_1.html</P>
<ul>
    <li>
        <a href="{% url 'polls:results' question_id %}">
            results
        </a>
    </li>
</ul>

polls/templates/polls/detail_2.html
<h1>{{ question.question_text }} 2</h1>
<ul>
{% for choice in choice_list %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/detail_3.html
<h1>{{ question.question_text }} 3</h1>
<form action="{% url 'polls:detail' question.id %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Vote">
</form>

polls/templates/polls/detail_4.html
<h1>{{ question.question_text }} 4</h1>
{{ form.non_field_errors }}
<form action="{% url 'polls:detail' question.id %}" method="post">
{% csrf_token %}
<p>
    {{ form.your_choice.label }}<br>
    {{ form.your_choice }}
</p>
<p>
    {{ form.new_option.label }}<br>
    {{ form.new_option }}
</p>
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% extends "myapp/base.html" %}
{% load static %}


{% block title %}Home{% endblock %}




{% block content %}

<h1>Polls App</h1>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">
            {{ question.question_text }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}


<p>This is the current directory path /polls/templates/polls/indx.html  ここにsample画像表示</p>
<img src="{{ MEDIA_URL }}/images/pc2022.png" alt="Your Image" width="700">




<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">



{% endblock %}

polls/templates/polls/login.html
{% extends "myapp/base.html" %}

{% load static %}


{% block title %}Home{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">

<h1>Please Login to Polls App.</h1>
<form action="{% url 'polls:login' %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Login">
</form>
<p>or <a href= "{% url 'polls:signup' %}">Sign Up</a></p>

{% endblock %}

polls/templates/polls/results.html
{% extends "myapp/base.html" %}

{% load static %}


{% block title %}Home{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">

<h1>{{ question.question_text }}</h1>
<p>{{ question.question_text }}　の投票数</p>
<ul>
{% for choice in question.choice_set.all %}
    <li>
    {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
    </li>
{% endfor %}
</ul>
<p>
    <a href="{% url 'polls:detail' question.id %}">Vote again</a> or
    <a href="{% url 'polls:index' %}">go back to top page</a>?
</p>
{% endblock %}

polls/templates/polls/signup.html
{% extends "myapp/base.html" %}

{% load static %}


{% block title %}Home{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">

<h1>Please Sign Up to Polls App.</h1>
<form action="{% url 'polls:signup' %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Sign Up">
</form>
<p>or <a href= "{% url 'polls:login' %}">Login</a></p>
{% endblock %}