album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('showall/', views.showall, name='showall'),
    path('upload/', views.upload, name='upload'),

]

main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import base
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('', include('myapp.urls')),  # myappのURLパターンを追加
    path('polls/', include('polls.urls')),
    path('album/', include('album.urls')),
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('accounts/login/', base.RedirectView.as_view(pattern_name="polls:login")),
    path('accounts/profile/', base.RedirectView.as_view(pattern_name="polls:index")),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

album/models.py
from django.db import models

class Image(models.Model):
    picture = models.ImageField(upload_to='images/')
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title


# Create your models here.

album/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['picture', 'title']

album/views.py
from django.shortcuts import render, redirect
from .models import Image
from .forms import ImageForm



def showall(request):
    images = Image.objects.all()
    context = {'images':images}
    return render(request, 'album/showall.html', context)

def upload(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('album:showall')
    else:
        form = ImageForm()

    context = {'form':form}
    return render(request, 'album/upload.html', context)

# album/views.py
from django.urls import path
from . import views

app_name = 'album'
urlpatterns = [
    path('showall/', views.showall, name='showall'),
    # 他のURLパターン
]

album/templates/album/showall.html
{% extends "myapp/base.html" %}

{% load static %}


{% block title %}Home{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">



<h1>Your Album</h1>


{% for image in images %}
    <img src='{{ MEDIA_URL }}{{image.picture}}' width=200>
    <h2>{{ image.title }}</h2>
{% endfor %}
<h2><a href="{% url 'album:upload' %}">Upload more</a></h2>

{% endblock %}

album/templates/album/upload.html
{% extends "myapp/base.html" %}

{% load static %}


{% block title %}Home{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">


<h1>Please Upload</h1>

<form enctype="multipart/form-data" action="{% url 'album:upload' %}" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Upload">
</form>

{% endblock %}