album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('showall/', views.showall, name='showall'),
    path('upload/', views.upload, name='upload'),

]

main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import base
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('', include('myapp.urls')),  # myappのURLパターンを追加
    path('polls/', include('polls.urls')),
    path('album/', include('album.urls')),
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('accounts/login/', base.RedirectView.as_view(pattern_name="polls:login")),
    path('accounts/profile/', base.RedirectView.as_view(pattern_name="polls:index")),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

myapp/models.py
from django.db import models

# Create your models here.
# models.pyです

myapp/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'myapp/index.html')

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> 
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> -->
    <title>{% block title %}Resort Page{% endblock %}</title>
</head>
<body><header><nav class="navbar navbar-dark bg-primary">
      <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
        <div class="container">
            <a class="navbar-brand" href="#">Resort Logo</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/album/showall/">album-image</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/">Rooms</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/">Dining</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Activities</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="polls/login/">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
    <div class="container">
       
        <div class="mt-4">
            {% block content %}{% endblock %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}

{% load static %}


{% block title %}Home{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">


<h1> My App </h1>

<p><a href="{% url 'polls:index' %}">アプリで投票しよう</a></p>
<P></P>
<p><a href="{% url 'album:showall' %}">画像アップロードアプリ</a></p>
<!-- <p><a href="http://localhost:8000/album/showall/">Go to Album Showall</a></p> -->

<p>This is the home page.
    <br>The current directory path is this.　 
    <br>main/myapp/templates/myapp/index.html
</p>
<p><img src="{{ MEDIA_URL }}/images/pc2022.png" alt="Your Image" width="700"></p>
{% endblock %}